# -*- coding: utf-8 -*-
"""FashIntellAlgorithm.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18TfuA5RggBGqsNh_ddYAxCTcc4fZNEqr
"""

import pandas as pd
import statistics

shape = pd.read_csv("shape_anno_all.txt", sep=" ", header=None, names=["SleeveLength", "LowerClothingLength", "Socks", "Hat", "Glasses", "Neckwear", "WristWearing", "Ring", "WaistAccessories", "Neckline", "Cardigan", "CoveringNavel"])
pattern = pd.read_csv("pattern_ann.txt", sep=" ", header=None, names=["UpperP", "LowerP", "OuterP"])
fabric = pd.read_csv("fabric_ann.txt", sep=" ", header=None, names=["UpperF", "LowerF", "OuterF"])
imageTypes = []
shape.dropna()
pattern.dropna()
fabric.dropna()
arr = list(set(list(shape.index) + list(fabric.index) + list(pattern.index)))
arr = [i for i in arr if type(i) == str]
for i in arr:
  if type(i) == int:continue
  imageTypes.append(i.split("_")[-1])
print(set(imageTypes))

def extractID(s):
  return s.split("_")[-3]
imgDict = {'front.jpg': 0, 'side.jpg': 1, 'back.jpg': 2, 'full.jpg': 3, 'additional.jpg': 4, 'flat.jpg': 5}

imgs = {}
for id in arr:
  a = extractID(id)
  if a in imgs:
    imgs[a][imgDict[id.split("_")[-1]]] = id
  else:
    imgs[a] = [""]*6
    imgs[a][imgDict[id.split("_")[-1]]] = id

imgDf = pd.DataFrame({"ID":[], 'front.jpg':[], 'side.jpg':[], 'back.jpg':[], 'full.jpg':[], 'additional.jpg':[], 'flat.jpg':[]})
for row in imgs:
  imgDf.loc[len(imgDf)] = ([row] + imgs[row])
display(imgDf)

imgDf.to_csv("imageData.csv")

for i in arr:
  if "00003111-02" in i or "00001494-03" in i:
    print(i)
    print(i.split("_")[-1])
    print(imgDict[i.split("_")[-1]])

genders = []
for i in arr:
  if type(i) == int:continue
  
  genders.append(i.split("-")[0])
print(set(genders))

ids = []
for i in arr:
   ids.append(i.split("_")[-3])
  #  print(i.split("_")[-3])

ids = set(ids)

df = pd.concat([shape.dropna(), fabric.dropna(), pattern.dropna()],axis = 1)
df = df.drop(columns=["Socks", "Glasses", "Neckwear", "WristWearing", "Ring", "Hat"])

genders = []
for i in df.index:
  genders.append(int("WOMEN" in i))
df["Gender"] = genders
df = df.dropna()
df = df.astype({'SleeveLength': 'int32', 'LowerClothingLength': 'int32', 'WaistAccessories': 'int32', 'Neckline': 'int32','Cardigan': 'int32','CoveringNavel': 'int32'})
# df.dropna()
# df.astype('int32').dtypes()
# len(set([extractID(i) for i in df.index]))
print(df.columns)
reviewed = {}
for i, row in df.iterrows():
  # print(reviewed)
  a = extractID(i)
  if a in reviewed:
    for j, val in enumerate(reviewed[a]):val.append(row[j])
  else:
    reviewed[a] = [[k] for k in row]

for i in reviewed:
  reviewed[i] = [statistics.mode(j) for j in reviewed[i]]

final = pd.DataFrame(columns=["ID",'SleeveLength', 'LowerClothingLength', 'WaistAccessories',
       'Neckline', 'Cardigan', 'CoveringNavel', 'UpperF', 'LowerF', 'OuterF',
       'UpperP', 'LowerP', 'OuterP', 'Gender'])
for i in range(len(reviewed)):
  final.loc[i] = [list(reviewed.keys())[i]] + list(reviewed.values())[i]
display(final)
# display(pd.DataFrame(reviewed))

a,b, c = final['Hat'].value_counts()
print(a / (a+b+c))

final.to_csv("clothingAttributes.csv")