# -*- coding: utf-8 -*-
"""sdk.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n01yqH8ZnPprfWUtczY96t6XL_1tkCaI
"""

pip install firebase-admin

import firebase_admin
from firebase_admin import credentials, storage
cred = credentials.Certificate('/content/fashintell-652d28c56175.json')
firebase_admin.initialize_app(cred,{
    'storageBucket': 'fashintell.appspot.com'
}, "test5")

# from google.cloud import storage
# from google.oauth2 import service_account
path = "MEN-Denim-id_00000080-01_7_additional.jpg"
# credentials = service_account.Credentials.from_service_account_file("/content/fashintell-652d28c56175.json")
# storage_client = storage.Client(credentials=credentials)
bucket = storage.bucket()
files = storage.Client(credentials=credentials).list_blobs(firebase_admin.storage.bucket().name) # fetch all the files in the bucket
print(files[0])

from google.cloud import storage
from google.oauth2 import service_account
import json

# def upload_blob(bucket_name, source_file_name, destination_blob_name):
#     credentials = service_account.Credentials.from_service_account_file("path/to/your/credentials.json")
#     storage_client = storage.Client(credentials=credentials)
#     bucket = storage_client.bucket(bucket_name)
#     blob = bucket.blob(destination_blob_name)
#     blob.upload_from_filename(source_file_name)
#     print(f"File {source_file_name} uploaded to {destination_blob_name}.")
# upload_blob(firebase_admin.storage.bucket().name, 'sample_image_file.jpg', 'images/beatiful_picture.jpg')
credentials = service_account.Credentials.from_service_account_file("/content/fashintell-652d28c56175.json")
files = storage.Client(credentials=credentials).list_blobs(firebase_admin.storage.bucket(name="fashintell.appspot.com").name) # fetch all the files in the bucket
imageObjects = list(files)
imageDict = {}
print(imageObjects[1].metadata)

def getI(s):
  for i, view in enumerate(["front", "side", "back", "full", "additional", "flat"]):
    if view in s:return i
  print(s)

def getID(s):
  return s.split("_")[-3]

for img in imageObjects[1:]:
  token = img.metadata["firebaseStorageDownloadTokens"]
  if getID(img.name) in imageDict:
    imageDict[getID(img.name)][getI(img.name)] = (img.public_url + "?alt=media&token=" + token).replace("storage.googleapis.com/fashintell.appspot.com/images/", "firebasestorage.googleapis.com/v0/b/fashintell.appspot.com/o/images%2F")
  else:
    imageDict[getID(img.name)] = [""]*6
    imageDict[getID(img.name)][getI(img.name)] = (img.public_url + "?alt=media&token=" + token).replace("storage.googleapis.com/fashintell.appspot.com/images/", "firebasestorage.googleapis.com/v0/b/fashintell.appspot.com/o/images%2F")

imageArr = []
for i in imageDict.values():
  imageArr.append(i)
# print(imageArr)
print(imageDict["00000867-01"])
with open("fashImages.json", "w") as outfile:
    json.dump(imageDict, outfile)
# json_object = json.dumps(imageDict, indent = 2) 
# print(json_object)